trigger:
  branches:
    include:
    - refs/heads/qa
schedules:
- cron: 49 7 * * *
  branches:
    include:
    - refs/heads/qa
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/qa
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
  - task: NodeTool@0
    displayName: Use Node 14.x
    inputs:
      versionSpec: 14.x
  - task: Npm@1
    displayName: Instalar dependências
    inputs:
      workingDir: automacao-aliare
      verbose: false
  - task: Npm@1
    displayName: Instalar cucumber
    inputs:
      command: custom
      workingDir: automacao-aliare
      verbose: false
      customCommand: i cypress-cucumber-preprocessor
  - task: Npm@1
    displayName: Executar teste E2E
    inputs:
      command: custom
      workingDir: automacao-aliare
      verbose: false
      customCommand: run cy:e2e:fulltest:run
  - task: Npm@1
    displayName: Executar teste API
    inputs:
      command: custom
      workingDir: automacao-aliare
      verbose: false
      customCommand: run cy:apis:fulltest:run
  - task: SpecFlowPlus@0
    displayName: 'SpecFlow+ build step. '
    inputs:
      projectFilePath: automacao-aliare/cypress/integration/gui
...